ulab-uiuc/research-town

README.md
=> feat(test): support codecov

.github/workflows/deploy_docs.yml, docs/docusaurus.config.js, docs/src/pages/index.js, pyproject.toml
=> ci(docs): deploy doc to website

.github/workflows/codespell.yml, .github/workflows/deploy_docs.yml, .github/workflows/isort.yml, .github/workflows/mypy.yml, .github/workflows/pytest.yml, .github/workflows/ruff.yml, .github/workflows/stale.yml
=> ci(all): unify workflow to be lowercase

.github/workflows/deploy_docs.yml
=> bug(ci): fix workflow name typo

.github/workflows/deploy_docs.yml, docs/CNAME, docs/docusaurus.config.js
=> bug(doc): fix website deploy

examples/research_town_demo.py, research_town/dbs/db_agent.py, research_town/dbs/db_base.py, research_town/dbs/db_paper.py, scripts/README.md, tests/dbs/test_dbs.py, tests/utils/test_retriever.py
=> feat(db): modify db embedding logic

.github/dependabot.yml
=> ci(bot): add docs dependency update

README.md
=> docs(readme): support star history

.github/workflows/codespell.yml, .github/workflows/isort.yml, .github/workflows/mypy.yml, .github/workflows/pytest.yml, .github/workflows/ruff.yml, README.md
=> ci(python): launch ci on more python version

tests/mocks/mocking_func.py
=> fix(mock): fix the mocking to support parsing

configs/default_config.yaml, research_town/agents/agent_base.py, research_town/configs/config.py
=> fix(proposal): update agentic writing with proposal

configs/config.yaml, examples/research_town_demo.py, examples/research_town_demo_log/ResearcherDB.json, research_town/agents/agent_base.py, research_town/configs/config.py, research_town/dbs/data.py, research_town/dbs/db_researcher.py, research_town/engines/engine.py, research_town/engines/engine_base.py, research_town/envs/env_base.py, research_town/envs/env_end.py, research_town/envs/env_experiments.py, research_town/envs/env_proposal_writing.py, research_town/envs/env_review_writing.py, research_town/envs/env_start.py, research_town/utils/role_verifier.py, tests/agents/test_agents.py, tests/configs/test_configs.py, tests/engines/test_engines.py, tests/envs/test_env_combination.py, tests/envs/test_envs.py, tests/utils/test_serializer.py
=> chore(name): update change role name

research_town/agents/agent_base.py, research_town/envs/env_base.py, research_town/envs/env_proposal_writing.py, research_town/envs/env_review_writing.py, research_town/envs/env_start.py, tests/agents/test_agents.py, tests/utils/test_serializer.py
=> feat(agent): delete base in research agent name

research_town/dbs/db_profile.py, research_town/envs/env_proposal_writing.py, research_town/envs/env_review_writing.py, research_town/envs/env_start.py, tests/dbs/test_dbs.py
=> fix(db): delete fixing role funcs

configs/config.yaml, examples/research_eval_demo.py
=> feat(config): change default to be gpt-4o-mini

README.md
=> fix(doc): update poetry install command

backend/main.py, research_town/agents/agent.py, research_town/dbs/data.py, research_town/dbs/db_profile.py, research_town/utils/agent_prompter.py
=> chore(prompter): move parser into prompter

backend/generator_func.py, backend/main.py
=> feat(backend): support backend progress serialize

README.md
=> doc(frontend, backend): add frontend backend instruction

examples/research_town_demo.py, research_town/agents/agent.py, research_town/envs/env_end.py, research_town/envs/env_proposal_writing.py, research_town/envs/env_review_writing.py, research_town/envs/env_start.py, research_town/utils/role_verifier.py, tests/envs/test_env_combination.py
=> feat(role): delete unnecessary role clarify

research_town/configs/config.py
=> fix(prompt): Fix 5q prompting

configs/agent_prompt.yaml, research_town/agents/agent.py, research_town/configs/config.py, research_town/utils/agent_prompter.py, tests/configs/test_configs.py
=> feat(prompt): condition idea generation on profile

configs/agent_prompt.yaml
=> fix(config): Add ethical prompting into the 'agent_prompt.yaml'

pyproject.toml
=> fix(docs): change a version name

pyproject.toml
=> fix(docs): update pyproject.toml

configs/agent_prompt/write_proposal_cot.yaml, configs/agent_prompt/write_proposal_react.yaml, configs/agent_prompt/write_proposal_reflexion.yaml
=> feat(prompt): update strategic prompting for 5q

configs/agent_prompt/write_proposal.yaml, configs/agent_prompt/write_proposal_cot.yaml, configs/agent_prompt/write_proposal_react.yaml, configs/agent_prompt/write_proposal_reflexion.yaml, configs/agent_prompt/write_rebuttal.yaml, configs/eval_prompt/idea_quality.yaml, configs/eval_prompt/insight_quality.yaml, configs/eval_prompt/metareview_quality.yaml, configs/eval_prompt/proposal_quality.yaml, configs/eval_prompt/rebuttal_quality.yaml, configs/eval_prompt/review_quality.yaml
=> feat(prompt): add few-shot example for proposal gen and modify eval prompt

pyproject.toml
=> chore(poetry): update version number for beta-2

backend/main.py, configs/agent_prompt/write_metareview_decision.yaml, configs/agent_prompt/write_metareview_ethical.yaml, configs/agent_prompt/write_metareview_strength.yaml, configs/agent_prompt/write_metareview_summary.yaml, configs/agent_prompt/write_metareview_weakness.yaml, research_town/agents/agent.py, research_town/configs/config.py, research_town/envs/env_review_writing.py, research_town/utils/agent_prompter.py, tests/agents/test_agents.py
Closes #592 
Remove rebuttal from metareview.
=> fix(prompt): remove rebuttal from metareview prompt

README.md, configs/param.yaml, docs/docs/api_ref/research_town.utils.md, research_town/configs/config.py, scripts/prompting_eval/eval.py, tests/agents/test_agents.py, tests/evaluators/test_evaluators.py, tests/utils/test_model_prompting.py, tests/utils/test_serializer.py
=> chore(config): delete together ai default value and delete result path

backend/main.py, frontend/src/components/InputForm.jsx, frontend/src/components/ProgressDisplay/ExpandableCard.jsx, frontend/src/components/ProgressDisplay/IdeaDisplay.jsx, frontend/src/components/ProgressDisplay/InsightDisplay.jsx, frontend/src/pages/Home.jsx
=> feat(frontend): add more instruction on UI

.github/workflows/aws-frontend.yml
=> fix(workflow): update backend url

frontend/src/components/InputForm.jsx, frontend/src/components/OutputDisplay.jsx, frontend/src/pages/Home.jsx
Closes #652
Dynamically show what the system is doing.
=> feat(frontend): dynamically show what the system is doing

.gitignore
=> chore(gitignore): add gitignore for research bench

.gitignore, configs/agent_prompt/write_rebuttal.yaml, frontend/src/components/ProgressDisplay/ProposalDisplay.jsx
=> fix(frontend): rebuttal results shows not correctly

backend/main.py, frontend/src/components/ProgressDisplay/IdeaDisplay.jsx, frontend/src/components/ProgressDisplay/ReviewDisplay.jsx
=> fix(frontend): support showing idea after discussion

poetry.lock, pyproject.toml
=> feat(poetry): prepare beta3

research_bench/utils.py
=> feat(bench): add single agent function

poetry.lock, pyproject.toml
=> fix(poetry): prepare release v0.0.1

research_town/envs/env_proposal_writing_with_rag.py, research_town/envs/env_proposal_writing_without_rag.py, research_town/envs/env_review_writing.py
=> feat(env): update input api for env

README.md, backend/app/extensions.py, backend/app/generator_func.py, backend/app/main.py
Closes #784  
This PR creates a single DB client instance and config object to be passed on to the engine for processing.
=> feat(backend): refactored backend for singleton db instance

research_town/utils/profile_collector.py
=> fix(profile): fix pub_abstracts type error

research_bench/proposal_writing.py, research_bench/run_evaluation.py, research_bench/utils.py, research_town/data/data.py, research_town/utils/paper_collector.py
=> feat(bench): support bench cache as a decorator

research_bench/mlbench.py
=> fix(bench): minor fix on mlbench

research_bench/create_bench_from_paper_links.py, research_bench/create_mlbench.sh
=> fix(bench): fix arxiv id process when eval

poetry.lock, pyproject.toml, research_bench/create_bench_from_conference.py, research_bench/utils.py, research_town/dbs/db_profile.py, research_town/utils/profile_collector.py
=> feat(bench): support using semantic scholar to build profile

research_bench/create_bench_from_conference.py, research_town/dbs/db_profile.py, research_town/utils/profile_collector.py
=> error handling

research_town/utils/profile_collector.py
=> minor_change

research_town/utils/profile_collector.py
=> logic modification

tests/utils/test_profile_collector.py
=> test modification

tests/dbs/test_dbs.py
=> test modify

research_bench/create_bench_from_paper_links.py, research_town/utils/profile_collector.py
=> feat(bench): make script multi-processing

research_bench/create_bench_from_paper_links.py
=> fix(bench): update parallel saving part

research_bench/create_bench_from_paper_links.py, research_town/utils/profile_collector.py
=> fix(bench): add number limit for semantic scholar search

research_bench/proposal_writing.py, research_bench/run_eval.py, research_bench/run_eval.sh
=> feat(bench): support sakana-ai proposal generation

research_town/envs/env_proposal_writing_with_rag.py, research_town/envs/env_proposal_writing_without_rag.py, research_town/envs/env_review_writing.py
=> fix(match): fix the error of must execut match

README.md, backend/app/extensions.py, pyproject.toml, research_town/dbs/db_provider/local/client.py, research_town/envs/env_proposal_writing_with_rag.py, research_town/envs/env_proposal_writing_without_rag.py, research_town/envs/env_review_writing.py
=> fix(readme): fix .env by using dotenv package

research_bench/eval.py, research_bench/proposal_writing.py, research_bench/run_eval.py, research_bench/run_eval.sh
=> fix(bench): sakana proposal writing Error

examples/research_town_demo.py
=> fix(demo): delete some comments in demo

research_bench/proposal_writing.py
Closes # 
- Apply param config of max new tokens;
- Fix response acquisition error;
- Prompt altered minimally.
=> fix(proposal_writing): fix sakana-baseline length and format error

research_bench/proposal_writing.py, research_bench/run_eval.py, research_bench/run_eval.sh
=> feat(bench): support zero-shot proposal writing

README.md
=> doc(readme): add links for dataset

README.md
=> docs(readme): add release news

README.md
=> docs(readme): modify titles

README.md
=> doc(readme): fix guidance errors in readme

README.md
=> feat(readme): update news
